<?php
/** Ejecuta las migraciones de esquema fuera de las peticiones HTTP. Uso: php tools/migrar.php */
if (PHP_SAPI !== 'cli') { fwrite(STDERR, "Este comando solo puede ejecutarse desde CLI.\n"); exit(1); }
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/Database.php';
$db = Database::getInstance();
try {
    $db->connect(DB_HOST, DB_USER, DB_PASS, DB_NAME);
    $db->execute("CREATE TABLE IF NOT EXISTS schema_migrations (version varchar(50) NOT NULL, applied_at timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci");
    $version = '001_legacy_schema_compatibility';
    if ($db->fetchOne('SELECT version FROM schema_migrations WHERE version = ?', [$version])) { echo "[OK] Migracion ya aplicada: {$version}\n"; exit(0); }
    $column = static function (string $table, string $name) use ($db): bool { $r=$db->fetchOne('SELECT COUNT(*) n FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? AND COLUMN_NAME=?',[DB_NAME,$table,$name]); return (int)($r['n']??0)>0; };
    $table = static function (string $name) use ($db): bool { $r=$db->fetchOne('SELECT COUNT(*) n FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=? AND TABLE_NAME=?',[DB_NAME,$name]); return (int)($r['n']??0)>0; };
    $index = static function (string $tableName, string $indexName) use ($db): bool { $r=$db->fetchOne('SELECT COUNT(*) n FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=? AND TABLE_NAME=? AND INDEX_NAME=?',[DB_NAME,$tableName,$indexName]); return (int)($r['n']??0)>0; };
    foreach ([['auditoria','ip_origen','VARCHAR(45) NULL'],['auditoria','ruta','VARCHAR(255) NULL'],['auditoria','metodo','VARCHAR(10) NULL'],['login_intentos','ultimo_intento','TIMESTAMP NOT NULL DEFAULT current_timestamp()'],['movimientos','documento_recepcion','VARCHAR(100) DEFAULT NULL AFTER status'],['usuarios','pin_emergencia',"VARCHAR(60) DEFAULT NULL COMMENT 'bcrypt hash de PIN 6 digitos de emergencia' AFTER respuesta_seguridad"],['login_intentos','usuario','VARCHAR(100) DEFAULT NULL AFTER ip_address']] as [$t,$c,$definition]) { if (!$column($t,$c)) { $db->execute("ALTER TABLE {$t} ADD COLUMN {$c} {$definition}"); echo "[OK] Columna {$t}.{$c}\n"; } }
    if (!$index('login_intentos','idx_ip_user_unique')) { if ($index('login_intentos','idx_ip_unique')) { $db->execute('DELETE FROM login_intentos WHERE id NOT IN (SELECT id FROM (SELECT MIN(id) id FROM login_intentos GROUP BY ip_address, usuario) x)'); $db->execute('ALTER TABLE login_intentos DROP INDEX idx_ip_unique'); } $db->execute('ALTER TABLE login_intentos ADD UNIQUE INDEX idx_ip_user_unique (ip_address, usuario)'); }
    $db->execute("CREATE TABLE IF NOT EXISTS solicitudes_compra (id_solicitud int(11) NOT NULL AUTO_INCREMENT,id_usuario_solicitante int(11) NOT NULL,fecha_solicitud timestamp NOT NULL DEFAULT current_timestamp(),motivo varchar(150) DEFAULT NULL,estado enum('Pendiente','Atendida','Cancelada') NOT NULL DEFAULT 'Pendiente',id_compra int(11) DEFAULT NULL,fecha_atendida datetime DEFAULT NULL,PRIMARY KEY(id_solicitud),KEY fk_sol_user(id_usuario_solicitante),KEY fk_sol_compra(id_compra),KEY idx_sol_estado(estado),CONSTRAINT fk_sol_user FOREIGN KEY(id_usuario_solicitante) REFERENCES usuarios(id_usuario),CONSTRAINT fk_sol_compra FOREIGN KEY(id_compra) REFERENCES compras(id_compra) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci");
    $db->execute("CREATE TABLE IF NOT EXISTS detalle_solicitud_compra (id_detalle int(11) NOT NULL AUTO_INCREMENT,id_solicitud int(11) NOT NULL,id_producto int(11) NOT NULL,cantidad_solicitada int(11) NOT NULL,PRIMARY KEY(id_detalle),KEY fk_dsc_solicitud(id_solicitud),KEY fk_dsc_producto(id_producto),CONSTRAINT fk_dsc_solicitud FOREIGN KEY(id_solicitud) REFERENCES solicitudes_compra(id_solicitud) ON DELETE CASCADE,CONSTRAINT fk_dsc_producto FOREIGN KEY(id_producto) REFERENCES productos(id_producto)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci");
    if (!$table('pagos_compra')) { $db->execute("CREATE TABLE pagos_compra (id_pago int(11) NOT NULL AUTO_INCREMENT,id_compra int(11) NOT NULL,id_usuario int(11) NOT NULL,monto decimal(10,2) NOT NULL,metodo_pago enum('Efectivo','Transferencia','Cheque','Otro') NOT NULL,detalle_pago json DEFAULT NULL,fecha_pago timestamp NOT NULL DEFAULT current_timestamp(),PRIMARY KEY(id_pago),KEY fk_pago_compra(id_compra),KEY fk_pago_usuario(id_usuario),CONSTRAINT fk_pago_compra FOREIGN KEY(id_compra) REFERENCES compras(id_compra) ON DELETE CASCADE,CONSTRAINT fk_pago_usuario FOREIGN KEY(id_usuario) REFERENCES usuarios(id_usuario)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci"); }
    foreach (['productos','compras','proveedores','clientes'] as $t) { if (!$column($t,'updated_at')) { $db->execute("ALTER TABLE {$t} ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"); echo "[OK] updated_at {$t}\n"; } }
    $normalization=$db->fetchOne("SELECT valor FROM configuracion WHERE clave='documentos_normalizados'"); if (!$normalization) { require_once __DIR__.'/../db/migrar_documentos.php'; migrar_documentos($db->getConnection(),DB_NAME); $db->execute("INSERT INTO configuracion (clave,valor,descripcion,fecha_actualizado) VALUES ('documentos_normalizados','1','Migracion de formato de documento fiscal aplicada (v1)',NOW()) ON DUPLICATE KEY UPDATE valor='1'"); }
    $db->execute('INSERT INTO schema_migrations(version) VALUES(?)',[$version]); echo "[OK] Migracion completada: {$version}\n";
} catch (Throwable $e) { fwrite(STDERR,"[ERROR] Migracion fallida: ".$e->getMessage()."\n"); exit(1); }